// <auto-generated />
namespace AHP.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class id : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(id));
        
        string IMigrationMetadata.Id
        {
            get { return "201907251654549_id"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
